/**
 * Heuristic value generation for discovery mode. There's no schema here, so — unlike
 * answer-gen.ts, which generates values per typed `ResponseDomain` — this guesses a plausible
 * answer purely from a DiscoveredField's kind and its best-effort label text. Pure and
 * browser-free so it's unit-testable without Playwright.
 *
 * Group kinds (radio-group/select/checkbox-group) return the actual `DiscoveredOption`(s) rather
 * than a plain value, since the caller needs `.selector` to act on the option — there's no
 * label-matching step to fall back on the way schema-adapter.ts has for the schema-guided path.
 */
import type { DiscoveredField, DiscoveredOption } from './types.js';

const PLACEHOLDER_LABEL_PATTERN = /^(-|--|select|choose|please select|pick one)\b/i;

function isPlaceholderOption(opt: DiscoveredOption): boolean {
  if (!opt.value) return true;
  return PLACEHOLDER_LABEL_PATTERN.test(opt.label.trim());
}

/** First option that doesn't look like a "-- Select --" placeholder; falls back to the first option. */
function firstRealOption(options: DiscoveredOption[]): DiscoveredOption | undefined {
  return options.find((o) => !isPlaceholderOption(o)) ?? options[0];
}

const LABEL_VALUE_HINTS: { pattern: RegExp; value: string }[] = [
  { pattern: /e-?mail/i, value: 'test@example.com' },
  { pattern: /phone|tel(ephone)?/i, value: '555-0100' },
  { pattern: /(zip|postal)\s*code/i, value: '90210' },
  { pattern: /first\s*name/i, value: 'Test' },
  { pattern: /last\s*name/i, value: 'Respondent' },
  { pattern: /\bname\b/i, value: 'Test Respondent' },
  { pattern: /\bcity\b/i, value: 'Springfield' },
  { pattern: /address/i, value: '123 Test Street' },
];

/** Generates a plausible answer for a discovered field, based on its kind and inferred label. */
export function generateDiscoveryValue(field: DiscoveredField): unknown {
  switch (field.kind) {
    case 'radio-group':
    case 'select':
      return firstRealOption(field.options ?? []);

    case 'checkbox-group': {
      const opt = firstRealOption(field.options ?? []);
      return opt ? [opt] : [];
    }

    case 'checkbox-single':
      return true;

    case 'email':
      return 'test@example.com';

    case 'tel':
      return '555-0100';

    case 'url':
      return 'https://example.com';

    case 'date':
      return new Date().toISOString().slice(0, 10);

    case 'number': {
      const min = field.min !== undefined && field.min !== '' ? Number(field.min) : undefined;
      const max = field.max !== undefined && field.max !== '' ? Number(field.max) : undefined;
      if (min !== undefined && max !== undefined) return Math.round((min + max) / 2);
      if (min !== undefined) return min;
      if (max !== undefined) return max;
      return 5;
    }

    case 'textarea':
      return clampLength('This is a test response generated by the Questionnaire Bot.', field.maxLength);

    case 'text':
    default: {
      for (const hint of LABEL_VALUE_HINTS) {
        if (hint.pattern.test(field.label)) return clampLength(hint.value, field.maxLength);
      }
      return clampLength('Test response', field.maxLength);
    }
  }
}

function clampLength(value: string, maxLength: number | undefined): string {
  if (maxLength !== undefined && maxLength > 0 && value.length > maxLength) {
    return value.slice(0, maxLength);
  }
  return value;
}
