export * from './types.js';
export { buildRegistry, buildCatalog, type BuildRegistryOptions } from './extract.js';
export {
  buildSearchIndex,
  search,
  type SearchIndex,
  type SearchOptions,
} from './search.js';
export {
  SupabaseCorpusSource,
  toRegistryEntry as corpusRowToEntry,
  corpusCitation,
  CORPUS_LICENSE,
  CORPUS_ATTRIBUTION,
  type CorpusMeta,
  type CorpusCode,
  type CorpusSearchRow,
  type CorpusSearchOptions,
  type CorpusSearchResult,
  type CorpusSourceConfig,
  type CorpusStats,
  type CorpusSurvey,
  type CorpusFilters,
  type CorpusConceptualVariable,
  type CorpusTimelineEntry,
  type CorpusConceptQuery,
  type CorpusConceptResult,
  type CorpusSuggestion,
  type CorpusSubjectFacet,
  type CorpusUnclassified,
  type CorpusDocument,
  type CorpusDocumentPage,
  corpusChunkStart,
  CORPUS_PAGES_PER_CHUNK,
} from './corpus.js';
