export * from './types.js';
export { buildRegistry, buildCatalog, type BuildRegistryOptions } from './extract.js';
export {
  buildSearchIndex,
  search,
  type SearchIndex,
  type SearchOptions,
} from './search.js';
export {
  SupabaseCorpusSource,
  toRegistryEntry as corpusRowToEntry,
  corpusCitation,
  isHarmonizedContent,
  isProcessVariable,
  CORPUS_LICENSE,
  CORPUS_ATTRIBUTION,
  type CorpusMeta,
  type CorpusAboutProgress,
  type CorpusCode,
  type CorpusSearchRow,
  type CorpusSearchOptions,
  type CorpusSearchResult,
  type CorpusDirectInput,
  type CorpusLineageTarget,
  type CorpusLineageTargetsPage,
  type CorpusLineageEdge,
  type CorpusSourceConfig,
  type CorpusStats,
  type CorpusSurvey,
  type CorpusFilters,
  type CorpusConceptualVariable,
  type CorpusTimelineEntry,
  type CorpusConceptContinuity,
  type CorpusConceptQuery,
  type CorpusConceptResult,
  type CorpusSuggestion,
  type CorpusSubjectFacet,
  type CorpusUnclassified,
  type CorpusDocument,
  type CorpusDocumentPage,
  corpusChunkStart,
  CORPUS_PAGES_PER_CHUNK,
} from './corpus.js';
