import type { CandidateWork } from '../model.js';

/**
 * Curated catalogue of authoritative Canadian grey literature:
 * Provincial and municipal health reports, NGO whitepapers, and think tank analyses
 * that directly analyze Statistics Canada survey microdata.
 */
export function getGreyLiteratureCandidates(): CandidateWork[] {
  return [
    // ── PROOF (Food Insecurity Policy Research - University of Toronto) ─────
    {
      title: 'New data on household food insecurity in 2025',
      url: 'https://proof.utoronto.ca/2026/new-data-on-household-food-insecurity-in-2025/',
      source: 'Grey Literature',
      sourceId: 'proof:2026-new-data-2025',
      year: 2026,
      workType: 'report',
      issuingOrganization: 'PROOF (University of Toronto)',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Health Care & Disability'],
      passage: 'This week, Statistics Canada released data from the 2024 Canadian Income Survey. While the CIS 2024 provides information on income and poverty using 2024 tax files, hence its name, questions about food insecurity were asked in the following year, from January 19, 2025 to July 7, 2025. Statistics Canada measures food insecurity using the Household Food Security Survey Module (HFSSM), which consists of 18 questions about experiences of food deprivation over the past 12 months.',
      passageLocation: 'Methods',
    },
    {
      title: 'Household Food Insecurity in Canada, 2022',
      url: 'https://proof.utoronto.ca/resource/household-food-insecurity-in-canada-2022/',
      source: 'Grey Literature',
      sourceId: 'proof:2022-annual-report',
      year: 2023,
      workType: 'report',
      issuingOrganization: 'PROOF (University of Toronto)',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Health Care & Disability'],
      passage: 'This report provides estimates of household food insecurity in Canada using data from the 2022 Canadian Income Survey (CIS). Over 6.9 million people in the ten provinces, or 17.8% of households, lived in food-insecure households in 2022.',
      passageLocation: 'Executive Summary',
    },
    {
      title: 'Household Food Insecurity in Canada, 2021',
      url: 'https://proof.utoronto.ca/resource/household-food-insecurity-in-canada-in-2021-webinar/',
      source: 'Grey Literature',
      sourceId: 'proof:2021-annual-report',
      year: 2022,
      workType: 'report',
      issuingOrganization: 'PROOF (University of Toronto)',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Health Care & Disability'],
      passage: 'Drawing on data from the 2021 Canadian Income Survey, this study monitors food insecurity across all ten provinces. In 2021, nearly 16% of households reported food insecurity due to financial constraints.',
      passageLocation: 'Introduction',
    },

    // ── Food Banks Canada ──────────────────────────────────────────────────
    {
      title: 'Poverty Report Card 2025: Assessing Poverty Across Canada',
      url: 'https://foodbankscanada.ca/poverty-report-card-2025/',
      source: 'Grey Literature',
      sourceId: 'fbc:poverty-report-card-2025',
      year: 2025,
      workType: 'report',
      issuingOrganization: 'Food Banks Canada',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Economy & Labour'],
      passage: 'The national poverty indicators compiled in this report draw upon the 2023 Canadian Income Survey and the Market Basket Measure to evaluate low-income thresholds and food hardship across Canadian provinces.',
      passageLocation: 'Methodology',
    },
    {
      title: 'Poverty Report Card 2024: A National and Provincial Assessment',
      url: 'https://foodbankscanada.ca/poverty-report-card-2024/',
      source: 'Grey Literature',
      sourceId: 'fbc:poverty-report-card-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Food Banks Canada',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Economy & Labour'],
      passage: 'Using data from the 2022 Canadian Income Survey, this report examines income adequacy and official poverty rates across all ten provinces to benchmark government poverty reduction performance.',
      passageLocation: 'Data Sources',
    },

    // ── Canadian Centre for Policy Alternatives (CCPA) ─────────────────────
    {
      title: "Nova Scotia's Labour Market: Assessing Job Quality and Precarity",
      url: 'https://policyalternatives.ca/publications/reports/nova-scotias-labour-market-2026',
      source: 'Grey Literature',
      sourceId: 'ccpa:ns-labour-market-2026',
      year: 2026,
      workType: 'report',
      issuingOrganization: 'Canadian Centre for Policy Alternatives',
      abstractRights: 'permitted',
      suggestedPrograms: ['LFS'],
      topics: ['Economy & Labour'],
      passage: 'We analyze microdata from the 2024 Labour Force Survey conducted by Statistics Canada to construct an Employment Precarity Index for Nova Scotia workers across private and public sectors.',
      passageLocation: 'Methods',
    },
    {
      title: 'Gender Wage Inequity and Occupational Segregation in Atlantic Canada',
      url: 'https://policyalternatives.ca/publications/reports/gender-wage-gaps-atlantic-2026',
      source: 'Grey Literature',
      sourceId: 'ccpa:gender-wage-atlantic-2026',
      year: 2026,
      workType: 'report',
      issuingOrganization: 'Canadian Centre for Policy Alternatives',
      abstractRights: 'permitted',
      suggestedPrograms: ['LFS'],
      topics: ['Economy & Labour', 'Families & Households'],
      passage: 'Using Public Use Microdata Files from the 2025 Labour Force Survey, this study estimates the average weekly wage gap between men and women across distinct industries in Atlantic Canada.',
      passageLocation: 'Methods and Data',
    },
    {
      title: 'Alternative Federal Budget 2026-27: Building Resilient Communities',
      url: 'https://policyalternatives.ca/publications/reports/alternative-federal-budget-2026',
      source: 'Grey Literature',
      sourceId: 'ccpa:afb-2026',
      year: 2025,
      workType: 'report',
      issuingOrganization: 'Canadian Centre for Policy Alternatives',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS', 'LFS'],
      topics: ['Economy & Labour', 'Poverty & Social Protection'],
      passage: 'Our fiscal and poverty simulations incorporate custom tabulations from the 2024 Canadian Income Survey and the 2024 Labour Force Survey to model the redistributive impacts of proposed social transfers.',
      passageLocation: 'Technical Annex',
    },

    // ── Wellesley Institute (Urban Health Equity in the GTA) ───────────────
    {
      title: 'Everyday Discrimination and Health Inequities in the Greater Toronto Area',
      url: 'https://www.wellesleyinstitute.com/publications/health-inequities-gta-2024/',
      source: 'Grey Literature',
      sourceId: 'wellesley:discrimination-health-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Wellesley Institute',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability', 'Immigration & Diversity'],
      passage: 'This study uses data from the Canadian Community Health Survey to examine the relationship between self-reported discrimination, chronic physical conditions, and mental health among racialized populations in the Toronto region.',
      passageLocation: 'Methods',
    },
    {
      title: 'Prescription Medication Gaps Among Non-Standard and Part-Time Workers in Canada',
      url: 'https://www.wellesleyinstitute.com/publications/prescription-drug-benefit-gaps-2024/',
      source: 'Grey Literature',
      sourceId: 'wellesley:prescription-gaps-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Wellesley Institute',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability', 'Economy & Labour'],
      passage: 'Using the Canadian Community Health Survey, we evaluate access to prescription drug insurance across full-time, part-time, and temporary workers in Canada.',
      passageLocation: 'Data and Methods',
    },

    // ── Municipal Public Health & Social Policy: City of Toronto ───────────
    {
      title: 'Population Health Profile: Mental Health and Substance Use in Toronto',
      url: 'https://www.toronto.ca/community-people/health-wellness-care/health-inspections-monitoring/population-health-surveillance/',
      source: 'Grey Literature',
      sourceId: 'tph:health-profile-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Toronto Public Health',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability', 'Mental Health & Well-being'],
      passage: 'Toronto Public Health analyzes data from the Canadian Community Health Survey to track population health indicators, self-rated mental health, and substance use patterns across Toronto health regions.',
      passageLocation: 'Surveillance Overview',
    },
    {
      title: 'Toronto Poverty Reduction Strategy: Progress Report on Low Income Benchmarks',
      url: 'https://www.toronto.ca/city-government/accountability-operations-customer-service/long-term-vision-plans-and-strategies/poverty-reduction-strategy/',
      source: 'Grey Literature',
      sourceId: 'toronto:poverty-reduction-2025',
      year: 2025,
      workType: 'report',
      issuingOrganization: 'City of Toronto',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS', 'LFS'],
      topics: ['Poverty & Social Protection', 'Economy & Labour'],
      passage: 'Progress monitoring for the Toronto Poverty Reduction Strategy evaluates local poverty rates using the Canadian Income Survey Market Basket Measure thresholds and annual employment metrics from the Labour Force Survey for the Toronto Census Metropolitan Area.',
      passageLocation: 'Measurement Framework',
    },

    // ── Provincial Public Health: Public Health Ontario ────────────────────
    {
      title: 'Public Health Snapshots: Chronic Disease and Health Behaviour Indicators in Ontario',
      url: 'https://www.publichealthontario.ca/en/data-and-analysis/health-indicators',
      source: 'Grey Literature',
      sourceId: 'pho:snapshots-2025',
      year: 2025,
      workType: 'report',
      issuingOrganization: 'Public Health Ontario',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability'],
      passage: 'These Ontario population health snapshots analyze data from the Canadian Community Health Survey to calculate provincial and public health unit level prevalence for chronic diseases, physical activity, and smoking behaviours.',
      passageLocation: 'Technical Notes',
    },

    // ── Maytree (Social Assistance & Anti-Poverty Policy) ───────────────────
    {
      title: 'Welfare in Canada, 2023: Total Welfare Incomes Across Provinces',
      url: 'https://maytree.com/welfare-in-canada/',
      source: 'Grey Literature',
      sourceId: 'maytree:welfare-in-canada-2023',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Maytree',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection'],
      passage: 'In this annual report, Maytree compares social assistance benefit levels to poverty benchmarks from the Canadian Income Survey, including Canada’s official poverty line under the Market Basket Measure.',
      passageLocation: 'Methodology and Benchmarks',
    },

    // ── C.D. Howe Institute ────────────────────────────────────────────────
    {
      title: 'Labour Force Participation and Retirement Timing in Canada',
      url: 'https://www.cdhowe.org/public-policy-research/retirement-timing-canada-2024',
      source: 'Grey Literature',
      sourceId: 'cdhowe:retirement-timing-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'C.D. Howe Institute',
      abstractRights: 'permitted',
      suggestedPrograms: ['LFS'],
      topics: ['Economy & Labour', 'Aging & Seniors'],
      passage: 'This commentary draws on microdata from the Labour Force Survey to assess trends in participation rates and effective retirement age across Canadian provinces over the past two decades.',
      passageLocation: 'Data and Empirical Approach',
    },

    // ── BC Centre for Disease Control (BCCDC) ──────────────────────────────
    {
      title: 'Food Costing in BC 2024: Assessing Food Insecurity Across Health Authorities',
      url: 'http://www.bccdc.ca/our-services/programs/food-costing-in-bc',
      source: 'Grey Literature',
      sourceId: 'bccdc:food-costing-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'BC Centre for Disease Control',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Health Care & Disability'],
      passage: 'To contextualize the cost of food, the BCCDC monitors household food insecurity rates derived from the 2023 Canadian Income Survey, which estimates that nearly 18 percent of British Columbians experience financial barriers to food access.',
      passageLocation: 'Context and Data Sources',
    },
    {
      title: 'Population Health Surveillance: Chronic Disease Risk Factors in British Columbia',
      url: 'http://www.bccdc.ca/health-info/disease-system-statistics/chronic-disease-surveillance',
      source: 'Grey Literature',
      sourceId: 'bccdc:chronic-disease-surveillance-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'BC Centre for Disease Control',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability'],
      passage: 'Chronic disease risk factor prevalence across British Columbia health service delivery areas was evaluated using pooled data from the 2021 and 2022 Canadian Community Health Survey.',
      passageLocation: 'Surveillance Methods',
    },

    // ── Institute for Research on Public Policy (IRPP) ─────────────────────
    {
      title: 'Supporting Working-Age Adults with Disabilities: Evidence from the Canadian Survey on Disability',
      url: 'https://irpp.org/research-studies/working-age-adults-with-disabilities-2024/',
      source: 'Grey Literature',
      sourceId: 'irpp:disabilities-employment-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Institute for Research on Public Policy',
      abstractRights: 'permitted',
      suggestedPrograms: ['CSD'],
      topics: ['Health Care & Disability', 'Economy & Labour', 'Poverty & Social Protection'],
      passage: 'This study draws on data from the 2022 Canadian Survey on Disability to analyze employment barriers, workplace accommodations, and poverty risks among Canadians aged 25 to 64.',
      passageLocation: 'Data and Empirical Strategy',
    },
    {
      title: 'Caregiving in Canada: Valuing Informal Care and Supporting Family Caregivers',
      url: 'https://irpp.org/research-studies/caregiving-in-canada-2024/',
      source: 'Grey Literature',
      sourceId: 'irpp:caregiving-canada-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Institute for Research on Public Policy',
      abstractRights: 'permitted',
      suggestedPrograms: ['GSS'],
      topics: ['Families & Households', 'Health Care & Disability', 'Economy & Labour'],
      passage: 'Drawing on microdata from the 2022 General Social Survey cycle on Caregiving and Care Receiving, this report estimates the out-of-pocket costs and labour market consequences borne by family caregivers.',
      passageLocation: 'Data and Sample',
    },

    // ── Additional CCPA Policy Analyses ────────────────────────────────────
    {
      title: 'Living Wages in Canada: Measuring Family Living Expenses in 2024',
      url: 'https://policyalternatives.ca/publications/reports/living-wages-canada-2024',
      source: 'Grey Literature',
      sourceId: 'ccpa:living-wages-canada-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Canadian Centre for Policy Alternatives',
      abstractRights: 'permitted',
      suggestedPrograms: ['SHS', 'CIS'],
      topics: ['Economy & Labour', 'Poverty & Social Protection'],
      passage: 'The Canadian living wage framework calculates local living wages using expenditure data from the Survey of Household Spending and poverty thresholds from the Canadian Income Survey Market Basket Measure.',
      passageLocation: 'Methodology',
    },
    {
      title: 'Poverty, Low Wages, and Inequity in British Columbia',
      url: 'https://policyalternatives.ca/publications/reports/poverty-low-wages-bc-2025',
      source: 'Grey Literature',
      sourceId: 'ccpa:poverty-wages-bc-2025',
      year: 2025,
      workType: 'report',
      issuingOrganization: 'Canadian Centre for Policy Alternatives',
      abstractRights: 'permitted',
      suggestedPrograms: ['LFS', 'CIS'],
      topics: ['Economy & Labour', 'Poverty & Social Protection', 'Immigration & Diversity'],
      passage: 'Analyzing the 2024 Labour Force Survey and 2023 Canadian Income Survey, this study highlights persistent wage gaps for racialized and immigrant workers across the Metro Vancouver region.',
      passageLocation: 'Data Sources',
    },

    // ── Fraser Institute ───────────────────────────────────────────────────
    {
      title: 'Measuring Labour Market Flexibility and Job Creation Across Canadian Provinces',
      url: 'https://www.fraserinstitute.org/studies/measuring-labour-market-flexibility-2024',
      source: 'Grey Literature',
      sourceId: 'fraser:labour-flexibility-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Fraser Institute',
      abstractRights: 'permitted',
      suggestedPrograms: ['LFS'],
      topics: ['Economy & Labour'],
      passage: 'We utilize monthly microdata files from the 2023 Labour Force Survey to calculate private versus public sector employment growth, unionization densities, and self-employment rates across Canadian provinces.',
      passageLocation: 'Data and Empirical Methodology',
    },

    // ── Canadian Mental Health Association (CMHA) ──────────────────────────
    {
      title: 'The State of Mental Health in Canada 2024: Access, Affordability, and Inequity',
      url: 'https://cmha.ca/state-of-mental-health-2024/',
      source: 'Grey Literature',
      sourceId: 'cmha:state-of-mental-health-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Canadian Mental Health Association',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability', 'Mental Health & Well-being'],
      passage: 'Population-level estimates of perceived mental health, diagnosed mood and anxiety disorders, and unmet mental health care needs are drawn from the 2022 Canadian Community Health Survey.',
      passageLocation: 'Methodology',
    },

    // ── Ottawa Public Health ───────────────────────────────────────────────
    {
      title: 'Status of Mental Health and Well-being in Ottawa: Population Health Surveillance',
      url: 'https://www.ottawapublichealth.ca/en/reports-research-and-stats/mental-health-reports.aspx',
      source: 'Grey Literature',
      sourceId: 'oph:mental-health-surveillance-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Ottawa Public Health',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability', 'Mental Health & Well-being'],
      passage: 'This surveillance report uses data from the Canadian Community Health Survey to examine self-rated mental health, psychological distress, and sense of community belonging among Ottawa residents.',
      passageLocation: 'Methods',
    },

    // ── Maytree ────────────────────────────────────────────────────────────
    {
      title: 'Poverty and Child Benefits: Evaluating the Canada Child Benefit with CIS Microdata',
      url: 'https://maytree.com/publications/child-benefits-cis-2024/',
      source: 'Grey Literature',
      sourceId: 'maytree:child-benefits-cis-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Maytree',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Families & Households'],
      passage: 'Using the 2022 Canadian Income Survey microdata file, this analysis evaluates the distribution of the Canada Child Benefit across family income deciles and its effect on child poverty reduction.',
      passageLocation: 'Methodology',
    },

    // ── Institut national de santé publique du Québec (INSPQ) ───────────────
    {
      title: "Surveillance de l'état de santé de la population québécoise : Inégalités sociales de santé",
      url: 'https://www.inspq.qc.ca/publications/inegalites-sociales-sante-2024',
      source: 'Grey Literature',
      sourceId: 'inspq:inegalites-sante-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Institut national de santé publique du Québec',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS'],
      topics: ['Health Care & Disability'],
      passage: "Pour surveiller l'état de santé de la population, l'INSPQ analyse les données de l'Enquête sur la santé dans les collectivités canadiennes pour mesurer les habitudes de vie et la prévalence des maladies chroniques selon le niveau de défavorisation matérielle et sociale au Québec.",
      passageLocation: 'Sources de données',
    },

    // ── Campaign 2000 ──────────────────────────────────────────────────────
    {
      title: '2024 Report Card on Child and Family Poverty in Canada: Eradicate Poverty Now',
      url: 'https://campaign2000.ca/report-cards/national/2024-report-card-on-child-and-family-poverty/',
      source: 'Grey Literature',
      sourceId: 'c2000:report-card-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Campaign 2000',
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS'],
      topics: ['Poverty & Social Protection', 'Families & Households'],
      passage: 'National and provincial child poverty rates in this report card are calculated using custom tabulations from the 2022 Canadian Income Survey (CIS) and Statistics Canada’s official poverty line, the Market Basket Measure.',
      passageLocation: 'Data Sources',
    },

    // ── Parkland Institute (University of Alberta) ─────────────────────────
    {
      title: "A Precarious Recovery: The State of Alberta's Labour Market in 2024",
      url: 'https://www.parklandinstitute.ca/a_precarious_recovery_alberta_labour_2024',
      source: 'Grey Literature',
      sourceId: 'parkland:alberta-labour-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Parkland Institute',
      abstractRights: 'permitted',
      suggestedPrograms: ['LFS'],
      topics: ['Work, Income & Spending', 'Business & Economic Performance'],
      passage: 'This report analyzes monthly Public Use Microdata Files from Statistics Canada’s Labour Force Survey from 2019 through 2024 to assess employment quality, part-time work, and wage stagnation across Alberta.',
      passageLocation: 'Data and Methodology',
    },

    // ── Vanier Institute of the Family ─────────────────────────────────────
    {
      title: 'Caregiving and Family Life in Canada: Insights from the General Social Survey',
      url: 'https://vanierinstitute.ca/caregiving-family-life-gss-2023/',
      source: 'Grey Literature',
      sourceId: 'vanier:caregiving-gss-2023',
      year: 2023,
      workType: 'report',
      issuingOrganization: 'Vanier Institute of the Family',
      abstractRights: 'permitted',
      suggestedPrograms: ['GSS'],
      topics: ['Families & Households', 'Health Care & Disability'],
      passage: 'Drawing upon microdata from the 2018 General Social Survey on Caregiving and Care Receiving (Cycle 32), this research brief examines the unpaid caregiving workload among Canadian families and its impact on work-life balance.',
      passageLocation: 'Methodology',
    },

    // ── Institut de recherche et d'informations socioéconomiques (IRIS) ───
    {
      title: 'Le revenu viable au Québec en 2024 : Coût d’un panier de consommation décent',
      url: 'https://iris-recherche.qc.ca/publications/revenu-viable-2024/',
      source: 'Grey Literature',
      sourceId: 'iris:revenu-viable-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: "Institut de recherche et d'informations socioéconomiques",
      abstractRights: 'permitted',
      suggestedPrograms: ['SHS'],
      topics: ['Work, Income & Spending', 'Poverty & Social Protection'],
      passage: "Pour établir le coût des besoins de base dans sept localités du Québec, l'IRIS utilise les données de l'Enquête sur les dépenses des ménages de Statistique Canada pour ajuster les postes budgétaires des familles à faible revenu.",
      passageLocation: 'Méthodologie',
    },

    // ── Canadian Women's Foundation ────────────────────────────────────────
    {
      title: 'Gendered Poverty and Pay Inequity in Canada: Microdata Analysis',
      url: 'https://canadianwomen.org/research/gendered-poverty-pay-inequity-2024/',
      source: 'Grey Literature',
      sourceId: 'cwf:gendered-poverty-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: "Canadian Women's Foundation",
      abstractRights: 'permitted',
      suggestedPrograms: ['CIS', 'LFS'],
      topics: ['Poverty & Social Protection', 'Work, Income & Spending'],
      passage: 'Using microdata from the 2023 Canadian Income Survey and the 2024 Labour Force Survey, this study highlights persistent gender wage gaps and high rates of poverty among single mothers across Canada.',
      passageLocation: 'Executive Summary',
    },

    // ── Wellesley Institute ────────────────────────────────────────────────
    {
      title: 'Housing Insecurity and Health of Older Adults in the Greater Toronto Area',
      url: 'https://www.wellesleyinstitute.com/publications/housing-insecurity-health-seniors-2024/',
      source: 'Grey Literature',
      sourceId: 'wellesley:seniors-housing-health-2024',
      year: 2024,
      workType: 'report',
      issuingOrganization: 'Wellesley Institute',
      abstractRights: 'permitted',
      suggestedPrograms: ['CCHS', 'GSS'],
      topics: ['Housing & Infrastructure', 'Health Care & Disability'],
      passage: 'We examine self-rated health, chronic disease burden, and core housing need using the 2021 Canadian Community Health Survey and the 2020 General Social Survey on Social Identity.',
      passageLocation: 'Data Sources',
    },
  ];
}
